### ISSUE TITLE
Can't Make

### ISSUE THREAD

**Issue by infiniteNIL** [Bogdanp/Noise#2]
I'm trying to build the libraries to try this out, but I get the following:

rod@Rods-MacBook-Pro-2021 Noise-racket-8.13 % make
make -C Lib libracketcs-universal-macos.a
lipo -create -output libracketcs-universal-macos.a libracketcs-arm64-macos.a libracketcs-x86_64-macos.a
fatal error: /Applications/Xcode-15.4.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: libracketcs-arm64-macos.a
make[1]: *** [libracketcs-universal-macos.a] Error 1
make: *** [Lib/libracketcs-universal-macos.a] Error 2

I'm using branch racket-8.13 and I have Racket 8.13 installed. You can see I'm using Xcode 15.4 and I have a Macbook Pro M1.

**Comment by Bogdanp** [comment]
It sounds like the LFS checkout might have failed. You can confirm this by running `file libracketcs-arm64-macos.a` and if it’s a text file then that’s what happened — another clue would be the file size. You should be able to run `git lfs fetch && git lfs checkout` to fix this.

**Comment by infiniteNIL** [comment]
Thank you. I just needed to setup LFS on my machine. After that I was able to work through things and get it to build.
